Assign.PL/Controllers/AssignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assign.BLL.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Assign.DAL.DataContext;
using Assign.DAL.Models;

namespace Assign.PL.Controllers
{
    public class AssignController : Controller
    {
        private readonly SdlabContext _context;
        private readonly IAssignService _assignmentService;

        public AssignController(SdlabContext context, IAssignService assignService)
        {
            _assignmentService = assignService;
            _context = context;
        }

        // GET: Assign
        public async Task<IActionResult> Index(int? labId)
        {
            if (labId.HasValue)
            {
                var assignments = await _assignmentService.GetAll(labId.Value);
                return View(assignments);
            }
            else
            {
                var sdlabContext = _context.Assignments.Include(a => a.LidNavigation);
                return View(await sdlabContext.ToListAsync());
            }
        }

        // GET: Assign/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Assignments == null)
            {
                return NotFound();
            }

            var assignment = await _assignmentService.GetAssignmentById(id.Value);
            if (assignment == null)
            {
                return NotFound();
            }

            return View(assignment);
        }

        // GET: Assign/Create
        public IActionResult Create()
        {
            ViewData["Lid"] = new SelectList(_context.Labs, "Lid", "Description");
            return View();
        }

        // POST: Assign/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Asid,Lid,AsName,Deadline,AsDesc")] Assignment assignment)
        {
            if (ModelState.IsValid)
            {
                _assignmentService.CreateAssignment(assignment);
                return RedirectToAction(nameof(Index));
            }
            ViewData["Lid"] = new SelectList(_context.Labs, "Lid", "Description", assignment.Lid);
            return View(assignment);
        }

        // GET: Assign/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Assignments == null)
            {
                return NotFound();
            }

            var assignment = await _assignmentService.GetAssignmentById(id.Value);
            if (assignment == null)
            {
                return NotFound();
            }
            ViewData["Lid"] = new SelectList(_context.Labs, "Lid", "Description", assignment.Lid);
            return View(assignment);
        }

        // POST: Assign/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Asid,Lid,AsName,Deadline,AsDesc")] Assignment assignment)
        {
            if (id != assignment.Asid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _assignmentService.UpdateAssignment(assignment.Asid, assignment.Lid.Value,assignment.AsName , assignment.Deadline,
                        assignment.AsDesc);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssignmentExists(assignment.Asid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Lid"] = new SelectList(_context.Labs, "Lid", "Description", assignment.Lid);
            return View(assignment);
        }

        // GET: Assign/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Assignments == null)
            {
                return NotFound();
            }

            var assignment = await _assignmentService.GetAssignmentById(id.Value);
            if (assignment == null)
            {
                return NotFound();
            }

            return View(assignment);
        }

        // POST: Assign/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Assignments == null)
            {
                return Problem("Entity set 'SdlabContext.Assignments'  is null.");
            }
            var assignment =  await _assignmentService.GetAssignmentById(id);
            if (assignment != null)
            {
                _assignmentService.DeleteAssignment(id);
            }
            
            return RedirectToAction(nameof(Index));
        }

        private bool AssignmentExists(int id)
        {
          return (_context.Assignments?.Any(e => e.Asid == id)).GetValueOrDefault();
        }
    }
}

Assign.PL/Controllers/LabController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assign.BLL.Services;
using Assign.BLL.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Assign.DAL.DataContext;
using Assign.DAL.Models;

namespace Assign.PL.Controllers
{
    public class LabController : Controller
    {
        private readonly SdlabContext _context;
        private readonly ILabService _labService;

        public LabController(SdlabContext context, ILabService labService)
        {
            _context = context;
            _labService = labService;
        }

        // GET: Lab
        public async Task<IActionResult> Index()
        {
            try
            {
                var labs = await _labService.GetAll();
                return View(labs);
            }
            catch
            {
                return Problem("An error occurred while retrieving the list of labs.");
            }
        }


        // GET: Lab/Details/5
        public async Task<IActionResult> Details(int id)
        {
            
            var lab = await _labService.FindLabById(id);

            return View(lab);
        }

        // GET: Lab/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Lab/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Lid,LabNo,Date,Title,Description")] Lab lab)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _labService.CreateLab(lab);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return Problem("An error occurred while adding the lab.");
                }
            }
            return View(lab);
        }

        // GET: Lab/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || _context.Labs == null)
            {
                return NotFound();
            }

            var lab = await _labService.FindLabById(id);
            if (lab == null)
            {
                return NotFound();
            }
            return View(lab);
        }

        // POST: Lab/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Lid,LabNo,Date,Title,Description")] Lab lab)
        {
            if (id != lab.Lid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _labService.UpdateLab(lab.Lid, lab.LabNo, lab.Date, lab.Title, lab.Description);
                }
                catch (ArgumentException ex)
                {
                    return NotFound(ex.Message);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lab);
        }


        // GET: Lab/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || _context.Labs == null)
            {
                return NotFound();
            }

            var lab = await _labService.FindLabById(id);
            if (lab == null)
            {
                return NotFound();
            }

            return View(lab);
        }

        // POST: Lab/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Labs == null)
            {
                return Problem("Entity set 'SdlabContext.Labs'  is null.");
            }

            //var lab = await _labService.FindLabById(id);
            if (id != null)
            {
                _labService.DeleteLab(id);
            }
            
            return RedirectToAction(nameof(Index));
        }

        private bool LabExists(int id)
        {
          return (_context.Labs?.Any(e => e.Lid == id)).GetValueOrDefault();
        }
    }
}

Assign.PL/Controllers/TokenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Assign.DAL.DataContext;
using Assign.DAL.Models;

namespace Assign.PL.Controllers
{
    public class TokenController : Controller
    {
        private readonly SdlabContext _context;

        public TokenController(SdlabContext context)
        {
            _context = context;
        }

        // GET: Token
        public async Task<IActionResult> Index()
        {
              return _context.Tokens != null ? 
                          View(await _context.Tokens.ToListAsync()) :
                          Problem("Entity set 'SdlabContext.Tokens'  is null.");
        }

        // GET: Token/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tokens == null)
            {
                return NotFound();
            }

            var token = await _context.Tokens
                .FirstOrDefaultAsync(m => m.TokId == id);
            if (token == null)
            {
                return NotFound();
            }

            return View(token);
        }

        // GET: Token/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Token/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TokId,Token1,Used")] Token token)
        {
            if (ModelState.IsValid)
            {
                _context.Add(token);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(token);
        }

        // GET: Token/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tokens == null)
            {
                return NotFound();
            }

            var token = await _context.Tokens.FindAsync(id);
            if (token == null)
            {
                return NotFound();
            }
            return View(token);
        }

        // POST: Token/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TokId,Token1,Used")] Token token)
        {
            if (id != token.TokId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(token);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TokenExists(token.TokId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(token);
        }

        // GET: Token/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tokens == null)
            {
                return NotFound();
            }

            var token = await _context.Tokens
                .FirstOrDefaultAsync(m => m.TokId == id);
            if (token == null)
            {
                return NotFound();
            }

            return View(token);
        }

        // POST: Token/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tokens == null)
            {
                return Problem("Entity set 'SdlabContext.Tokens'  is null.");
            }
            var token = await _context.Tokens.FindAsync(id);
            if (token != null)
            {
                _context.Tokens.Remove(token);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TokenExists(int id)
        {
          return (_context.Tokens?.Any(e => e.TokId == id)).GetValueOrDefault();
        }
    }
}

Assign.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Assign.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Assign.PL.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
  
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - Assign.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Assign.PL/Views/Shared/_LayoutNoNavBar.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assign.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assign.PL.styles.css" asp-append-version="true" />
</head>
<body>
<header>
    
</header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Assign.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Assign.PL/Views/Shared/_LayoutStudents.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assign.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assign.PL.styles.css" asp-append-version="true" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assign.PL</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="IndexStudents">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Submission" asp-action="Create">Create Submission</a>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Submission" asp-action="Index">View Submissions</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">View Students & Edit Details</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Assign.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Assign.PL/Views/Shared/_LayoutTeacher.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assign.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assign.PL.styles.css" asp-append-version="true" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assign.PL</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="IndexTeachers">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Lab" asp-action="Index">Edit Labs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Create">Create Students</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Assign" asp-action="Index">Edit Assignments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Token" asp-action="Index">Edit Tokens</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Edit Teachers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Attend" asp-action="Index">Edit Attendances</a>
                    </li>


                </ul>
            </div>
        </div>
    </nav>
</header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Assign.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>